CONTENT_SERVER_DOMAIN_NAME = "ftp.nulabgroup.com.au"
CONTENT_SERVER_FTP_LOGIN = "SCO800"
CONTENT_SERVER_FTP_PASSWORD = "vvF95Cq1TK"

CONTENT_SERVER_SFTP_DOMAIN_NAME = "110.142.207.74"
CONTENT_SERVER_SFTP_LOGIN = "pocketprints"
CONTENT_SERVER_SFTP_PASSWORD = "eNrcJ56CCD"